### ISSUE TITLE
[RFC] Consistent style for commit titles

### ISSUE THREAD

**Issue by JamiKettunen** [Arsen6331/lure-repo#16]
I do rather like how the commits to [`void-packages`](https://github.com/void-linux/void-packages/commits/master) are done, would it be too much of a hassle for contributors to start using something consistent? I propose these commit titles:
- Adding a new package: `${name}: new package (${version})`
  - Example: `strelaysrv: new package (1.18.6)`
- Updates to existing  package: `${name}: update to ${version}`
  - Example: `strelaysrv: update to 1.22.1`
- Other changes to a package: `${name}: some other changes, enable feature, ...`
  - Example: `strelaysrv: fix cheksums`

The important thing is the `${name}: ` prefix on each commit title, even on updates you could suffix it with `, something else` if it's important enough to state in the commit title. The extended commit message itself would still be free-form.

Having the titles standardized would make the commit history nice to read and you can tell at a glance what is going on in each as well :)

**Comment by Arsen6331** [comment]
The issue is that there's no way to enforce the usage of these commit messages, there will be some contributors just not using them because they either forgot or didn't read the documentation.

**Comment by jansheikkinen** [comment]
> The issue is that there's no way to enforce the usage of these commit messages, there will be some contributors just not using them because they either forgot or didn't read the documentation.

What if the commit format is just a strong recommendation, instead of a requirement? If the goal is nice-to-read commit history, I personally feel like that goal can be easily achieved so long as _most_ commits follow the format.

**Comment by iamwacko** [comment]
> The issue is that there's no way to enforce the usage of these commit messages, there will be some contributors just not using them because they either forgot or didn't read the documentation.

You could also try squashing PR's and using consistent commit title there.
