### ISSUE TITLE
lure installed using `lure-bin` package cannot refresh this repo

### ISSUE THREAD

**Issue by SinTan1729** [Arsen6331/lure-repo#29]
It's showing me that the version number is lower than specified in the repo. Indeed, `lure version` returns `0.0.4-*` instead of `0.0.5`. `lure-git` works as expected.

**Comment by JamiKettunen** [comment]
Hm it should just warn about `lure` being out of date and that things might not work properly as per https://github.com/Arsen6331/lure/commit/3437df8676d9697fca587b9ab0d2f6395637cb4f (but at the very least still allowing updates to both `lure-bin` and `lure-git` as those shouldn't be sprinkled with new `lure.sh` or whatever features for a while to allow people to update them with `lure` itself), perhaps @Arsen6331 has an idea?

**Comment by Arsen6331** [comment]
Yeah, it should be allowing updates just fine. That message is just a warning. What happened when you tried to update the LURE?

**Comment by SinTan1729** [comment]
I updated it manually. Now it seems to work if I reinstall it.
